using Cysharp.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Threading;
using UnityEngine;
using UnityEngine.Networking;
using YooAsset;

public class GameStart : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    async void Start()
    {
        Debug.Log("GameStart");
        GamePreload.Inst.Test("call by GameStart");
        _=FrameSplittingTest(1);
        await UIManager.Inst.ShowUIAsync<SimpleR3Test>("test1", MainUICanvas.Inst.Medium);
    }
    async UniTask FrameSplittingTest(int delayFrame)
    {
        for (int i = 0; i < 100; i++)
        {
            Debug.Log(i);
            await UniTask.DelayFrame(delayFrame);
        }
    }
}